create database aula4;
USE aula4;

-- DATETIME  - `2023-03-03 13:50:01`
-- TINYINT -  0-255
-- DEFAULT - CONFIGURAÇAO PADRAO DO CAMPO
CREATE TABLE PROFESSOR (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
ESPECIALIDADE VARCHAR(40) DEFAULT 'SEM ESPECIALIDADE',
GENERO CHAR(1) CONSTRAINT CHKGENERI CHECK 
(GENERO IN ('F','M','N')),
DTATUAL DATETIME DEFAULT CURRENT_TIMESTAMP,
STTATUAL TINYINT );

SELECT*FROM PROFESSOR;

INSERT INTO PROFESSOR (GENERO) VALUES
('M');

INSERT INTO PROFESSOR ( NOME, STTATUAL ) VALUES
('DELL VALE', '0'),
('TANG', '1'),
('SUKITA', '2');

UPDATE PROFESSOR SET STTATUAL = 1 WHERE ID= 4;

ALTER TABLE PROFESSOR ADD CONSTRAINT CHKSTTATUAL CHECK (STTATUAL IN (0,1));

DELETE FROM PROFESSOR WHERE ID = 4;

INSERT INTO PROFESSOR ( NOME, STTATUAL ) VALUES
('KISUCO', '1');
SELECT * FROM PROFESSOR;

ALTER TABLE PROFESSOR AUTO_INCREMENT = 1000;
INSERT INTO PROFESSOR (NOME, ESPECIALIDADE) VALUES
('COCA','COLA');
SELECT * FROM PROFESSOR;

-- O PROFESSOR COM NOME XPTO TEM A ESPECIALIDADE x

SELECT concat(' O PROFESSOR COM NOME ', NOME, ' TEM A ESPECIALIDADE ', ESPECIALIDADE) FROM PROFESSOR;

-- APELIDAR (ALIAS)

SELECT concat(' O PROFESSOR COM NOME ', NOME, ' TEM A ESPECIALIDADE ', ESPECIALIDADE) AS FRASE FROM PROFESSOR;
SELECT NOME AS 'NOME DO PROFESSOR' FROM PROFESSOR;
SELECT ESPECIALIDADE AS ESPECIAL, STTATUAL AS 'STATUS ATUAL' FROM PROFESSOR;

DESC PROFESSOR;

SELECT * FROM PROFESSOR;