use sptech;

-- CAMPOS DO TIPO NUMERICO --
-- NUMEROS INTEIROS (INT)
-- NUMEROS DECIMAIS 
-- FLOAT: 7 DIGITOS 1234567
-- DOUBLE: 15 DIGITOS 123456789012345
-- DECIMAL(TOTAL, QTD-NUMEROS-APÓS-VIRGULA)
-- DECIMAL(5,2) 123,45
-- DECIMAL (7,4) 123,4567

CREATE TABLE PESSOA(
ID INT PRIMARY KEY auto_increment,
NOME VARCHAR(50) NOT NULL,
PESO FLOAT,
ALTURA FLOAT,
SALARIO DECIMAL (5,2),
CONSTRAINT CHKSALARIO CHECK (SALARIO >= 0)
)AUTO_INCREMENT = 100;
DESCRIBE TABLE PESSOA;

DESC PESSOA;

-- CONSTRAINT (RESTRIÇAO / CONFIGURAÇAO DOS CAMPOS)
-- CHECK
-- NOT NULL
-- PRIMARY KEY

-- CHECK PESO E ALTURA
ALTER TABLE PESSOA 
ADD CONSTRAINT CHKPESO CHECK (PESO >=0),
ADD CONSTRAINT CHKALTURA CHECK (ALTURA >=0);

-- ESSES COMANDOS TEM QUE DAR ERRO SE FOR NEGATIVO

INSERT INTO PESSOA VALUES
(NULL,'MARCOS',90.4,210,-9.90);

INSERT INTO PESSOA VALUES
(NULL,'DURANT', 90.4,210, 399.99),
(NULL,'HORTENCIA', 78.6,174, 99.99),
(NULL,'OSCAR', 110.2,205, 99.99);

SELECT * FROM PESSOA WHERE NOME LIKE '__R%'; 

-- EXIBIR AS PESSOAS CUJO A ALTURA E DIFERENTE DE 210

SELECT * FROM PESSOA WHERE ALTURA <> 210;  -- OU --
SELECT * FROM PESSOA WHERE ALTURA != 210;

-- DELETAR INSERÇAO DE DADOS FEITA DUAS VEZES 

DELETE FROM PESSOA WHERE ID = '5';
DELETE FROM PESSOA WHERE ID = '6';
DELETE FROM PESSOA WHERE ID = '4';
SELECT * FROM PESSOA;

-- EXIBIR PESSOAS CUJO A ALTURA E IGUAL 210 OU 205

SELECT * FROM PESSOA WHERE ALTURA = 210 OR ALTURA = 205; -- OU --
SELECT * FROM PESSOA WHERE ALTURA IN (210,205);

-- ATUALIZAÇAO DE TABELA

UPDATE PESSOA SET SALARIO = 199.99
WHERE ID IN (2,3);

INSERT INTO PESSOA VALUES
(NULL, 'JAMES', 115,212, 999.99);


-- APAGAR TODAS AS CONFIGURAÇOES E DADOS DA TABELA --
TRUNCATE TABLE PESSOA; 


-- APOS O TRUNCATE A INSERÇAO DE DADOS VOLTA AO INCREMENT 1, POIS ELIMINOU TODA A CONFIGURAÇAO. --

INSERT INTO PESSOA VALUES
(NULL, 'JORDAN', 99.7,199, 976.90);
SELECT * FROM PESSOA;

DESC PESSOA;

