CREATE DATABASE SPRINT2;
USE SPRINT2;

CREATE TABLE ATLETA (
IDATLETA INT PRIMARY KEY auto_increment,
NOME VARCHAR (40),
MODALIDADE VARCHAR (40),
QTDMEDALHA INT
);

INSERT INTO ATLETA VALUES
(NULL, 'CARLOS', 'FUTEBOL', 14),
(NULL, 'CAUE', 'FUTEBOL', 4),
(NULL, 'ARTHUR', 'ATLETISMO', 9 ),
(NULL, 'GABRIEL', 'ATLETISMO', 4 );

SELECT * FROM ATLETA;

UPDATE ATLETA SET QTDMEDALHA = 9
WHERE IDATLETA IN (1);

UPDATE ATLETA SET QTDMEDALHA = 5
WHERE IDATLETA IN (2,3);

UPDATE ATLETA SET NOME = 'MATHEUS'
WHERE IDATLETA IN (4);

ALTER TABLE ATLETA ADD COLUMN DTNASC DATE;

UPDATE ATLETA SET DTNASC = 19990512
WHERE IDATLETA IN (1);

UPDATE ATLETA SET DTNASC = 19800512
WHERE IDATLETA IN (2);

UPDATE ATLETA SET DTNASC = 19990702
WHERE IDATLETA IN (3);

UPDATE ATLETA SET DTNASC = 19990111
WHERE IDATLETA IN (4);

SELECT * FROM ATLETA;

DELETE FROM ATLETA WHERE IDATLETA = 4;

SELECT * FROM ATLETA WHERE MODALIDADE != 'NATACAO';

SELECT * FROM ATLETA WHERE QTDMEDALHA >= 3;

ALTER TABLE ATLETA MODIFY MODALIDADE VARCHAR (80);

DESCRIBE ATLETA;

TRUNCATE TABLE ATLETA;




