USE SPRINT2;
CREATE TABLE MUSICA (
IDMUSICA INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR (40),
ARTISTA VARCHAR (40), 
GENERO VARCHAR (40)
);

select * from MUSICA;
insert into MUSICA values
(NULL, 'Carolina foi para o samba(Carolina)', 'Luiz o', 'Forro'),
(NULL, 'Pra dançá o xenhenhém(Carolina)', 'Poderoso', 'Forro'),
(NULL, 'Todo mundo é caidinho(Carolina)', 'Chefão', 'Forromix'),
(NULL, 'Pelo cheiro que ela tem(Carolina)', 'Remix', 'Forromix'),
(NULL, 'Hum, hum, hum', 'Luiz o', 'rastachinela'),
(NULL, 'Carolina, hum, hum, hum', 'Poderoso', 'rastachinela'),
(NULL, 'Carolina, hum, hum, hum', 'Chefão', 'piseiro'),
(NULL, 'Pelo cheiro que ela tem (Carolina)', 'Remix', 'piseiro');

select * from MUSICA;

ALTER TABLE MUSICA ADD COLUMN CURTIDAS INT;

UPDATE MUSICA SET CURTIDAS = '5'
WHERE IDMUSICA IN (1);

UPDATE MUSICA SET CURTIDAS = '6'
WHERE IDMUSICA IN (2);

UPDATE MUSICA SET CURTIDAS = '5'
WHERE IDMUSICA IN (3);

UPDATE MUSICA SET CURTIDAS = '1'
WHERE IDMUSICA IN (4);

UPDATE MUSICA SET CURTIDAS = '12'
WHERE IDMUSICA IN (5);

UPDATE MUSICA SET CURTIDAS = '9'
WHERE IDMUSICA IN (6);

UPDATE MUSICA SET CURTIDAS = '4'
WHERE IDMUSICA IN (7);

UPDATE MUSICA SET CURTIDAS = '65'
WHERE IDMUSICA IN (8);

select * FROM MUSICA;

ALTER TABLE MUSICA MODIFY ARTISTA VARCHAR (80);
DESC MUSICA;

UPDATE MUSICA SET CURTIDAS = '9'
WHERE IDMUSICA IN (1);

UPDATE MUSICA SET CURTIDAS = '4'
WHERE IDMUSICA IN (2,3);
SELECT * FROM MUSICA;

UPDATE MUSICA SET TITULO = 'CAROLINAAAA HUM HUM'
WHERE IDMUSICA IN (5);
SELECT * FROM MUSICA;

DELETE FROM MUSICA WHERE IDMUSICA = 4;
SELECT * FROM MUSICA;

SELECT * FROM MUSICA WHERE GENERO != 'FUNK';

SELECT * FROM MUSICA WHERE CURTIDAS >='20';

DESCRIBE MUSICA;

TRUNCATE TABLE MUSICA;