USE SPRINT2;
CREATE TABLE FILME (
IDFILME INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR (50),
GENERO VARCHAR (40),
DIRETOR VARCHAR (40)
);
DESC FILME;
insert into Filme values
(NULL, 'Gato de botas', 'desenho', 'claudio'),
(NULL, 'Atirador', 'ação', 'claudio'),
(NULL, 'senhor dos aneis', 'medieval', 'marcos'),
(NULL, 'harry potter', 'bruxaria', 'marcos'),
(NULL, 'maze runner', 'ação', 'Carlos'),
(NULL, 'zumbilandia', 'comedia', 'claudia'),
(NULL, 'zumbilandia 2', 'comedia', 'claudia'),
(NULL, 'sherek', 'desenho', 'carlos');

SELECT * FROM FILME;
ALTER TABLE FILME ADD COLUMN PROTAGONISTA VARCHAR(40);

UPDATE FILME SET PROTAGONISTA = 'JOAO'
WHERE IDFILME IN (1);

UPDATE FILME SET PROTAGONISTA = 'MARIA'
WHERE IDFILME IN (2);

UPDATE FILME SET PROTAGONISTA = 'CLAUDIO'
WHERE IDFILME IN (3);

UPDATE FILME SET PROTAGONISTA = 'SERGIO'
WHERE IDFILME IN (4);

UPDATE FILME SET PROTAGONISTA = 'ANA'
WHERE IDFILME IN (5);

UPDATE FILME SET PROTAGONISTA = 'MARCELA'
WHERE IDFILME IN (6);

UPDATE FILME SET PROTAGONISTA = 'KAMILA'
WHERE IDFILME IN (7);

UPDATE FILME SET PROTAGONISTA = 'IVONETE'
WHERE IDFILME IN (8);

SELECT * FROM FILME;

ALTER TABLE FILME modify COLUMN DIRETOR VARCHAR (150);

UPDATE FILME SET DIRETOR = 'MARCELO'
WHERE IDFILME IN (5);

UPDATE FILME SET DIRETOR = 'MARCELINHO'
WHERE IDFILME IN (2);

UPDATE FILME SET DIRETOR = 'MARCELAAAO'
WHERE IDFILME IN (7);
SELECT * FROM FILME;

UPDATE FILME SET TITULO = 'MUNDO DOS MACACOS'
WHERE IDFILME IN (4);

DELETE FROM FILME WHERE IDFILME IN (3);

SELECT * FROM FILME WHERE GENERO != 'DRAMA';
SELECT * FROM FILME WHERE GENERO = 'SUSPENSE';
DESC FILME;
TRUNCATE TABLE FILME;


