USE SPRINT2;
CREATE TABLE REVISTA (
IDREVISTA INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (40),
CATEGORIA VARCHAR (30));
select * from revista;

insert into revista (nome) values
('Veja'),
('Isto É'),
('Quatro Rodas'),
('Epoca');

SELECT * FROM REVISTA;

UPDATE REVISTA SET CATEGORIA = 'NOTICIAS'
WHERE IDREVISTA IN (1);

UPDATE REVISTA SET CATEGORIA = 'NOTICIAS'
WHERE IDREVISTA IN (2);

UPDATE REVISTA SET CATEGORIA = 'AUTOMIBILISTICA'
WHERE IDREVISTA IN (3);

UPDATE REVISTA SET CATEGORIA = 'NOTICIAS'
WHERE IDREVISTA IN (4);

INSERT INTO REVISTA VALUES
(NULL, 'FOLHA', 'NOTICIAS'),
(NULL, 'ESTADAO', 'NOTICIAS'),
(NULL, 'RECREIO', 'TEEN');
SELECT * FROM REVISTA;

DESC REVISTA;

ALTER TABLE REVISTA MODIFY COLUMN CATEGORIA VARCHAR (40);
ALTER TABLE REVISTA ADD COLUMN PERIODICIDADE VARCHAR (15);
SELECT * FROM REVISTA;
ALTER TABLE REVISTA DROP column PERIODICIDADE;
SELECT * FROM REVISTA;
